### PR TITLE
related updates to API section of README

### PR DESCRIPTION
**Pull request by saphirasnow**
updates API section to match model description

### CODE REVIEW

**Review by gramliu — DISMISSED** [review]
Looks good. I like the change to using `code` markers. It makes it a lot more readable

**Review by gramliu — CHANGES_REQUESTED** [review]
Actually looking at the improved model a bit more, I don't think we're using `G3` as an input feature (we shouldn't either). Instead, we're using it to determine the expected value and thus, to measure the accuracy of the model. I think it would be better to update the description under the *Input Features* section to reflect this -- that we're only using `health`, `absences`, `age`, and `G2` to train the model and that `G3` is simply used to measure the accuracy of our model.

**Comment by thisisalbertliang** [comment]
> Actually looking at the improved model a bit more, I don't think we're using `G3` as an input feature (we shouldn't either). Instead, we're using it to determine the expected value and thus, to measure the accuracy of the model. I think it would be better to update the description under the _Input Features_ section to reflect this -- that we're only using `health`, `absences`, `age`, and `G2` to train the model and that `G3` is simply used to measure the accuracy of our model.

You are right Gram. It's a typo in the README. Thanks for catching this. G3 is not an input feature. I have removed all G3 related text in the README now.

**Comment by thisisalbertliang** [comment]
LGTM. I will merge now

**Review by thisisalbertliang — APPROVED** [review]

**Pull request merged**
