### PR TITLE
add new model with improved f1 score

### LINKED ISSUE #1: Train ML model to predict student success
Train the ML model on the selected features and pickle it for loading into the microservice

### LINKED ISSUE #2: Determine features for ML model
Determine which features to use in the ML model

### PR DESCRIPTION
**Pull request by thisisalbertliang**
Resolve #1 

The new model is a random forest classifier that additionally takes G2 as an input feature. As a result, the f1 score is improved from 0.5185185185185185 to 0.9861111111111112.

The new model is saved as a pickle file under dockerfile/apps folder.

### CODE REVIEW

**Review by saphirasnow — CHANGES_REQUESTED** [review]
Could you also change the README to reflect the new list of parameters, so we know for sure what that list is?

**Comment by thisisalbertliang** [comment]
> Could you also change the README to reflect the new list of parameters, so we know for sure what that list is?

Right. I have added Model Description to the README. This resolves the "(b) A description of which features you used in training your model, and how your retrained the model performs better than the baseline model" README requirement in the HW4 Part B.

Please approve if nothing else is needed.

**Review by saphirasnow — CHANGES_REQUESTED** [review]
Please check over #10 (the PR I made to this branch with changes to API section of README) to ensure it matches. If that's good, I think we can merge that to this and this to main.

**Comment by thisisalbertliang** [comment]
> Please check over #10 (the PR I made to this branch with changes to API section of README) to ensure it matches. If that's good, I think we can merge that to this and this to main.

Ok great. I am merging this one into main.

**Pull request merged**
